### ISSUE TITLE
Registering throws an error

### ISSUE THREAD

**Issue by trovster** [euperia/htg-laravel#1]
I tried to register and I was given an error;

	ErrorException in User.php line 80:
	
	Trying to get property of non-object (View: /Users/trovster/Sites/htg-laravel/resources/views/layouts/main.blade.php) (View: /Users/trovster/Sites/htg-laravel/resources/views/layouts/main.blade.php)

going to the root path also shows the same error.

I visited http://localhost:8000/auth/logout which then showed me the login/register options.

**Comment by euperia** [comment]
Thanks.

**Comment by euperia** [comment]
Missing a command in install instructions.  You need to run:

    php artisan db:seed

After running the migrate command.  @trovster can you try this and close the issue if it worked for you? Thanks.
